export default {
  maschio: [
    'Ogni giocatore femmina prende una penna e fa un disegno di massimo 5cm quadrati su un tuo braccio o su una tua gamba',
    'Vota il giocatore donna che secondo te ha le labbra più carnose',
    'Verità! Bevi per dimenticare soldato! Bevi x1/2 per ogni volta che ti hanno lasciato.',
    'Premio per chi si distingue dalla massa; se hai i capelli lunghi bevi x1/2! Come dici? Non è un premio? Ah scusa... va beh bevilo lo stesso.',
    'Scegli se una ragazza ti dovrà tirare uno schiaffo oppure bevi x1!',
    'Fatti mettere il rossetto sulle labbra da una ragazza oppure bevi x1',
    "Comunque sta cosa che i maschi sono più alti delle ragazze non l'ho mica capita... Stai seduto sotto il tavolo per i prossimi 5 minuti",
    'Indossa una collana o un bracciale femminile finché la ragazza che ti ha imprestato ciò non dovrà bere x1',
    'Se hai a disposizione dei sandali da uomo indossali per i prossimi 5 turni. E comunque pessimo gusto.',
    "E' risaputo i maschietti reggono di più, quindi bevi x1 per essere alla pari con le ragazze!",
    'Tieni le mani come se impugnassi una pistola per i prossimi 3 minuti',
    'Sei obbligato a rispondere ad una verità scelta dalle ragazze... A meno che tu non voglia bere x1!,Lanciate tutti un dado chi fa meno beve x1. (In caso di parità tra alcuni giocatori ci sarà uno spareggio solo tra loro)',
    'Indossa una cravatta,Bevi x1/2!',
    'Solleva un peso di almeno 3 kg 10 volte per braccio,Bevi x1!',
    'Solleva un peso di almeno 3 kg 15 volte per braccio,Bevi x1 e 1/2!',
    'Fingi di essere un bodygard fuori da una discoteca per i prossimi 5 minuti quindi stai in piedi, auricolare in un orecchio e braccia conserte. (Se una prossima sfida necessita di altre posture potrai stoppare momentaneamente questa e riprenderla una volta possibile)',
    'Prova a effettuare quante più flessioni con il giocatore più leggero sdraiato sulla tua schiena... Lo so è impossibile, ma tu provaci!',
    'Mettiti momentaneamente una corda o una sciarpa legata intorno alla fronte come fossi Rambo e poi imita il suo "Adrianaaaa!"',
    'Senza rilevare a nessuno che taglia hai e senza farti vedere quanto bevi, dovrai bere in base alla taglia delle mutande che indossi solitamente; XS:0 S:x1/2 M:x1 L:x1e1/2 XLe+:x2',
    'Bevi per il numero equivalente alla quantità di tette femminili che sono presenti nella stanza ora, diviso 4!',
    'Fai alzare tutte le ragazze in piedi e per ognuna di esse dovrai inchinarti e fare un baciamano,A turno in ordine cronologico partendo da te dovete dire una parola terminante in -OTA entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
  ],
  unisex: [
    'Bevi x1 se hai fratelli o sorelle',
    'Lancia un dado; pari bevi x1 dispari non bevi',
    'Lancia due volte un dado; se entrambe le volte esce lo stesso numero bevi x1',
    'BONUS! Per i prossimi tre turni successivi a questo se dovrai bere dimezzerai la tua bevuta (Valido solo per i prossimi tre turni)',
    "I giocatori del sesso opposto al tuo dovranno scegliere all'unisono una canzone con il cantante di sesso opposto al tuo da farti cantare per almeno 10 secondi imitandone anche la voce",
    'A turno in ordine cronologico partendo da te dovete dire una parola terminante in -ITA entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
    'A turno in ordine cronologico partendo da te dovete dire una parola terminante in -ETA entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
    'A turno in ordine cronologico partendo da te dovete dire una parola terminante in -EGO entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
    'A turno in ordine cronologico partendo da te dovete dire una parola terminante in -LDI entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
    'A turno in ordine cronologico partendo da te dovete dire una parola terminante in -OVO entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
    'A turno in ordine cronologico partendo da te dovete dire una parola terminante in -OCA entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
    'A turno in ordine cronologico partendo da te dovete dire una parola terminante in -ECA entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
    'A turno in ordine cronologico partendo da te dovete dire una parola terminante in -OGO entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
    'A turno in ordine cronologico partendo da te dovete dire una parola terminante in -REA entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
    'A turno in ordine cronologico partendo da te dovete dire una parola terminante in -UMO entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
    'A turno in ordine cronologico partendo da te dovete dire una parola terminante in -PIO entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
    'A turno in ordine cronologico partendo da te dovete dire una parola terminante in -AGO entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
    'A turno in ordine cronologico partendo da te dovete dire una parola terminante in -LTO entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
    'A turno in ordine cronologico partendo da te dovete dire una parola terminante in -PRA entro 10 secondi. Il gioco si ferma quando qualcuno ripete una parola già detta o non ha più idee il quale dovrà beve x1!',
    'Fai una capriola o bevi x1',
    'Fai la ruota o bevi x1/2',
    'Fai la verticale o bevi x1/2',
    'Fai 10 addominali',
    'Scegli un giocatore che ti tenga i piedi saldi mentre fai 10 addominali in modo preciso e lentamente',
    'Gara di durata Plank tra tutti i giocatori chi perde beve x1!',
    'Riproduci un brano che conosci a memoria a velocità x1.25 se già veloce di suo o x1.5 se abbastanza lenta e cantala provando a star dietro a quella velocità',
    "Cantaci a cappella per almeno 10 secondi la prima canzone che ti viene in mente imitando la voce dell'artista",
    'MALUS! Se nel prossimo turno a questo qualcuno dovrà bere dividerà in modo equo la sua bevuta con te',
    "Per 90 secondi spegnete la luce mettete una luce strobo tramite torcia del telefono e riproducete della musica da discoteca a volume un po' alto. Ballate e comportatevi tutti come foste in discoteca!",
    'Sei un dj! Fino a nuovo ordine scegli te la musica da mettere in sottofondo!',
    'Capo della notte! Fino a nuovo ordine scegli della musica da mettere in sottofondo!',
    'Create tutti insieme in modo proporzionale una playlist di almeno 15 tracce totali e riproducetela fino a nuovo ordine!',
    'Fai vibrare il cuore di tutti! Trova una playlist su App/Internet di musica Dance e riproducila fino a nuovo ordine!',
    'Siamo tutti con te fratello! Trova una playlist su App/Internet di musica Rap/Trap e riproducila fino a nuovo ordine!',
    'Tunz Tunz parapara Tunz Tunz! Trova una playlist su App/Internet di musica Techno o minimal e riproducila fino a nuovo ordine!',
    "Cattura l'anima di tutti! Trova una playlist su App/Internet di musica Rock e riproducila fino a nuovo ordine!",
    'Scegli una radio su internet su canale televisivo o tramite app e riproducila fino a nuovo ordine!',
    'Giocate a morra cinese sasso i perdenti bevono x1/2!',
    'Il giocatore che ha più follower su Instagram beve x1/2 mentre il giocatore che ha meno follower beve x1!',
    'Chi ha Tik Tok installato sul telefono beve x1!',
    'Quanti giocatori hanno un telefono android? Quanti invece hanno IOS? La minoranza beve x1/2!',
    'Stai in piedi per i prossimi 3 turni',
    'Siediti a terra per i prossimi 3 turni',
    'Scegli un giocatore a cui dovrai dare le spalle stando in piedi a pochi centimetri da lui per i prossimi 3 turni',
    'Chi percepisce lo stipendio più alto beve x1! Stronzo!',
    'A turno in ordine cronologico partendo da te dovete dire una parola che abbia le prime 3 lettere uguali alle 3 lettere finali della parola detta dalla persona precedente a te. Chi ripete o non ha idee entro 10 secondi beve x1! Inizi te con una parola a tua scelta ma che dia la possibilità di proseguire in modo semplice il gioco.',
    'Salta... non ti chiedere il perché salta e basta.',
    'Bacia sulla guancia il giocatore più lontano a te',
    'Abbraccia per 20 secondi il giocatore più lontano a te',
    "Chiedi a un assistente vocale di scegliere un numero compreso tra 0 e 20 e inizia una conta partendo da te (da 1) in ordine cronologico fino al numero detto dall'assistente vocale. Chi esce dovrà bersi x1/2!",
    'Se avete a disposizione una maschera dovrai indossarla per i prossimi 10 turni',
    'Il prossimo turno in cui tu sarai esente dalla sfida la dovrai passare ballando il tip tap',
    'Il prossimo turno in cui tu sarai esente dalla sfida la dovrai passare ballando il un lento con una persona immaginaria',
    'Il prossimo turno in cui tu sei esente dalla sfida dovrai ballare il cha cha cha',
    'STOP ALLA MUSICA! Non so se avete in sottofondo della musica sono una semplice applicazione ma se per caso qualcuno sta riproducendo della musica la stoppi immediatamente!',
    "Mettiti un bicchiere riempito per metà con dell'acqua in equilibrio sulla testa e non farlo cadere per almeno 30 secondi (scegli un bicchiere di carta o plastica... non vorremo mai che il bicchiere si rompesse mettendo a repentaglio la tua misera vita)",
    'Se tu sei uscito dalla stanza bevi x1/2!',
    'Scegli un giocatore con cui inventare un saluto simpatico da ricordare negli annali',
    'Per i prossimi 5 minuti parli dando del lei agli altri giocatori',
    'Per i prossimi 5 minuti parli in un dialetto scelto da te',
    'Per i prossimi 5 minuti parli come fossi un orientale in vacanza in Italia',
    'Per i prossimi 5 minuti parli come fossi un britannico in vacanza in Italia',
    'Per i prossimi 5 minuti parli come fossi un tedesco in vacanza in Italia',
    'Per i prossimi 5 minuti parli come fossi un cambogiano in vacanza in Italia',
    'Se entrambi i tuoi genitori provengono da regioni o stati diversi dal posto in cui sei nato bevi x1!',
    "La prossima volta che dovrai bere berrai dal bicchiere di un'altra persona scelta da te!",
    'Mima il titolo di un film chi indovina entro 30 secondi vince e riceve un abbraccio da te',
    'Chi ha pagato da bere è esente dal bere per questo turno gli altri bevono x1/2',
    'Testa o croce? Se indovini dimezzerai la tua prossima bevuta',
    'Testa o croce? Se sbagli bevi x1/2',
    'Chi ha brontolato per giocare a questo gioco beve x1/2!',
    'Verità! Avessi a disposizione 3 desideri dal genio della lampada cosa sceglieresti di fare? (Non si possono moltiplicare i desideri)',
    'Verità! Vincessi alla lotteria una cifra pari a 1 milione di euro come utilizzeresti quel denaro?',
    'Verità! Stai pensando di acquistare qualcosa di particolare in questo periodo? Se sì cosa?',
    'Verità! Raccontaci una tua bella figura di merda',
    'Se indossi un indumento rosso bevi x1/2! A meno che non sia capodanno... in quel caso non ne bevi 1/2 ma x1!',
    'Verità! Raccontaci la tua ultima multa presa',
    'Raccontaci una barzelletta',
    'Raccontaci una freddura',
    'Chi ha i capelli rossi beve x1!',
    'Chi è calvo beve x1!',
    'Il meno abbronzato beve x1',
    'Facci vedere 3 piroette',
    'Verità! Elenca tutti gli sport fatti nella tua vita',
    'Fino a che non berrai alzati e balla',
    'Mangia mezzo cucchiaino di sale',
    'Mangia 1 cucchiaio di zucchero',
    'Verità! Ti sei mai ubriacato da solo?',
    'Prova a toccarti il naso con la lingua',
    'Dì un insulto diverso per ogni giocatore',
    'Con la persona persona più vicina a te guardatevi intensamente negli occhi se uno dei due sorride o ride entro 1 minuto beve x1!',
    'Quanti abitanti abitano stabilmente il Polo Sud? Se indovini in un range di 200 persone la prossima volta che dovrai bere dimezzerai la tua bevuta',
    'Quanti abitanti abitano stabilmente il Polo Nord? Se indovini in un range di 500.000 persone la prossima volta che dovrai bere dimezzerai la tua bevuta',
    'Per i prossimi 5 turni ogni volta che vorrai parlare ti dovrai alzare in piedi',
    'Chi non ha mai un trillo con MSN beve x1!',
    'Se fumi offri una sigaretta a tutti i giocatori che ne vogliono una.',
    'Bevi x1/2 per ogni A presente nel tuo nome!',
    'Bevi x1/2 per ogni E presente nel tuo nome!',
    'Bevi x1/2 per ogni I presente nel tuo nome!',
    'Bevi x1/2 per ogni O presente nel tuo nome!',
    'Bevi x1/2 per ogni U presente nel tuo nome e nel tuo cognome!',
    'Non importa quanto sia pieno... finisci il tuo bicchiere.',
    'Fai il ballo del robot per 15 secondi con musica dance in sottofondo',
    'Se non vivi più con i tuoi bevi x1!',
    "Per i prossimi 5 minuti ogni volta che dovrai parlare dovrai farlo sussurrando all'orecchio di un altro giocatore",
    'La prossima volta che dovrai bere non potrai usare le mani (Puoi farti aiutare da un altro giocatore)',
    'Rispondi alla prima storia che trovi sula bacheca di Instagram o bevi x1!',
    'Per i prossimi 5 turni parlerai con un accento snob',
    "Leggici l'ultimo messaggio che hai inviato alla quinta conversazione su Whatsapp in ordine partendo dall'alto e spiegane il motivo o bevi x1!",
    "Leggici l'ultimo messaggio che hai inviato alla sesta conversazione su Whatsapp e spiegane il motivo o bevi x1!",
    "Leggici l'ultimo messaggio che hai inviato alla quarta conversazione su Whatsapp e spiegane il motivo o bevi x1!",
    "Leggici l'ultimo messaggio che hai inviato alla ventesima conversazione su Whatsapp e spiegane il motivo o bevi x1!",
    'Bevi un cucchiaio di olio o bevi x1',
    'Bevi un cucchiaio di aceto o bevi x1!',
    'Mangia un uovo crudo dal guscio o bevi x1!',
    'Fischietta una canzone finché qualcuno non la riconosce. Se non sai fischiare o dopo vari tentativi nessuno indovina nessuna canzone che stai fischiettando bevi x1!',
    'Siediti sotto al tavolo per i prossimi 5 turni',
    'Appoggia la testa sulla spalla del giocatore più prossimo alla tua sinistra per 5 minuti',
    'Sai muovere le orecchie senza toccartele? Facci vedere!',
    'Indossa una tua scarpa come fosse un guanto per i prossimi 5 turni',
    'Facci vedere un tuo sguardo sexy',
    'Fai due giri del tavolo a quattro zampe o bevi x1',
    'Bendatevi tutti e disegnate una zebra su un foglietto avete 40 secondi di tempo poi votate il migliore',
    'Bendatevi tutti e disegnate un elicottero su un foglietto avete 45 secondi di tempo poi votate il migliore',
    'Bendati e disegna un neonato che beve dal biberon su un foglietto hai 45 secondi di tempo',
    'Bendati e disegna un elefante in equilibrio su un pallone da circo su un foglietto hai 45 secondi di tempo',
    'Bendatevi tutti e disegnate un grattacielo su un foglietto avete 45 secondi di tempo poi votate il migliore',
    'Bendati e disegna una strega che mescola il suo calderone su un foglietto hai 45 secondi di tempo',
    "Per i prossimi 3 turni comportati come una persona dell'età come la tua ma con i numeri invertiti (Es. Se hai 18 anni inverti i numeri quindi comportati come avessi 81 anni)",
    'Verità! Hai mai pianto vedendo un film?',
    "Verità! Hai mai sboccato per colpa dell'alcool? Se sì quante volte?",
    'Cerca la tua immagine più vecchia che hai pubblicato su Facebook o su Instagram falla vedere a tutti i giocatori altrimenti bevi x1/2!',
    'Verità! Raccontaci di una tua paura',
    'Verità! Sei mai scappato di casa?',
    'Verità! Sei mai scappato senza pagare?',
    'Ora sei un manager musicale! Da ora in poi scegli tu la musica ma deve essere di un solo artista!',
    'Facci vedere una foto di una persona anche che non conoscete che rappresenta per te la perfezione fisica',
    'Mangia qualcosa senza usare le mani',
    'Fai vedere che non sei ignorante! Recita tutta o una parte di poesia che sai a memoria...',
    'Che fai te la rischi? Puoi bere x2 adesso e se nei prossimi 5 round capita che dovrai bere non berrai (le sfide non sono esenti)',
    'Imita per 20 secondi il verso di un animale scelto dai giocatori',
    'Chi non ha la patente beve x1! Se tutti avete la patente il giocatore più tardivo (a livello di età) beve x1!',
    'Verità! Russi la notte?',
    'Verità! Hai mai fatto il sunnanbolo?',
    'Se avete animali in casa mangia mezzo cucchiaino del suo cibo oppure bevi x1!',
    "Verità! Qual'è l'ultima cosa che hai rubato?",
    "Verità! Qual'è l'ultima volta che hai fatto a botte con qualcuno?",
    'Verità! Raccontaci un tuo sogno ricorrente o in alternativa il sogno più strano che hai fatto.',
    'Quanto te la rischi? Puoi scegliere se bere x1 per fare bere una persona che vuoi te x2!',
    'Quanto te la rischi? Puoi scegliere se bere x1 per fare bere tutti i giocatori x1/2!',
    'Devi chiudere assolutamente ora gli occhi! Fallo ora! Ora che hai gli occhi chiusi dicci che ore pensi che siano se sbagli per un massimo di 15 minuti non ti succede nulla se sbagli per più di 15 minuti bevi x1!',
    'Il giocatore che in questo momento ha la gradazione alcolica più bassa nel proprio bicchiere beve x1! In caso di pareggio i giocatori con la gradazione alcolica più bassa bevono x1/2!',
    'Per i prossimi 3 turni tutti potete parlare solo con suoni onomatopeici che sentite solitamente nei cartoni animati senza parole',
    "L'ultimo giocatore ad aver sboccato per colpa dell'alcool beve x1!",
    'Imita 5 versi di animali',
    'Imita 10 versi di animali',
    "Descrivi la tua immagine di profilo su WhatsApp per 1 minuto parlandone come fosse un quadro e tu fossi un critico d'arte.",
    'Il/la proprietario/a di casa invita tutti a dormire da lui/lei per questa sera oppure beve x1! Se accetta di invitare tutti a dormire chi risponderà di no berrà x1 chi accetta è salvo!',
    'Finché non berrai dovrai pronunciare anche la punteggiatura mentre parli',
    'Finché non berrai dovrai parlare dicendo il contrario di quello che pensi',
    'Al prossimo turno in cui ti verrà data la scelta tra fare una sfida e bere dovrai scegliere di fare la sfida! Segnatelo da qualche parte prima che te lo dimentichi',
    'Bevi x1 se sei figlio unico',
    'Lancia un dado, la cifra che ottieni dividila per 3... ed ecco! Il risultato sarà la quantità di bevute che dovrai bere! (Si approssima sempre per difetto a una precisione dello 0,5). Esempio: il risultato del dado è 5, 5÷3=1,6 che approssimato diventa 1,5. Se il risultato del dado fosse 4 invece sarebbe 4÷3=1,3 che approssimato sarebbe 1.',
    "Rimani bendata per i prossimi 5 minuti. (Se nelle prossime sfide viene necessariamente richiesto l'uso della vista, potrai stoppare il tempo e sbendarti per il periodo strettamente necessario, mentre se è possibile risolvere l",
    "Rimani bendata per i prossimi 10 minuti. (Se nelle prossime sfide viene necessariamente richiesto l'uso della vista, potrai stoppare il tempo e sbendarti per il periodo strettamente necessario, mentre se è possibile risolvere la sfida tramite la guida degli altri giocatori allora non dovrai sbenda",
    "Rimani bendata per i prossimi 15 minuti. (Se nelle prossime sfide viene necessariamente richiesto l'uso della vista, potrai stoppare il tempo e sbendarti per il periodo strettamente necessario, mentre se è possibile risolvere la sfida tramite la guida degli altri giocatori allora non dovrai sbenda",
    "Rimani bendata per i prossimi 20 minuti. (Se nelle prossime sfide viene necessariamente richiesto l'uso della vista, potrai stoppare il tempo e sbendarti per il periodo strettamente necessario, mentre se è possibile risolvere la sfida tramite la guida degli altri giocatori allora non dovrai sbenda",
    'Partendo da te in senso orario dovrete dire un sinonimo della parola "guardare\\',
    'Tutti eccetto te bevono x1/2!',
    'BONUS! Per la sola prossima vo',
    'BONUS! Se al turno successivo dovrai bere tu, non berrai! (Valido solo per il turno successivo a questo)',
    'BONUS! Per i prossimi due turni successivi a questo sei immune dal bere (Valido solo per i prossimi due turni)',
    'Per ogni giocatore di sesso maschile, baciati nella mano e soffia come se v',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "SPORT" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "STORIA" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "ANIMALI" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "SCOPERTE E INVENZIONI" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "CIBO E BEVANDE" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "ALCOOL" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "MULTINAZIONALI MILIARDARIE" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "INDUSTRIA PORNOGRAFICA" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "SISTEMA SOLARE" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "SMARTPHONE E COMPUTER" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "APP SOCIAL" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "GEOGRAFIA" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "CLASSIFICHE MONDIALI O EUROPEE TRA STATI" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "POLITICA" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore a cui devi fare una qualsiasi domanda di cultura generale sul argomento "MUSICA" dandogli 2 possibili risposte tra cui scegliere, una sola di queste è esatta e se la sbaglia dovrà bere x1! Per pensare alla domanda da porre puoi consultare internet.',
    'Scegli un giocatore con cui giocare a "blocca pollice" alla meglio di 3, chi perde fa 3 piegamenti',
    'Fai 10 ripetizioni di "Crunch Inverso\\',
    'Ballate fino alla fine del ritornello il ballo di gruppo "Bomba" con un video tutorial davanti',
    'Ballate fino alla fine del ritornello il ballo di gruppo "Mueve la colita\\',
    'Ballate fino alla fine del ritornello il ballo di gruppo "Gangnam Style\\',
    'Apri l\'App di Tik Tok e imita i primi 6 video in ordine di come si presentano (Se non hai Tik Tok cerca un video su altre piattaforme e senza prima sceglierli cerca esempio "balli Tik Tok" ed effettua i primi 6)',
    'Chiedi a un assistente vocale di scegliere un numero compreso tra 0 e 25, il numero che uscirà sarà il quantitativo di "affondi frontali" che dovrai fare come penitenza! Pensala positivo, rispetto a una bevuta fa bene alla salute!',
    'Chiedi a un assistente vocale di scegliere un numero compreso tra 0 e 25, il numero che uscirà sarà il quantitativo di "sumo squat con tocco del pavimento" che dovrai fare come penitenza! Pensala positivo, rispetto a una bevuta fa bene alla salute!',
    'Apri Instagram e commenta sotto il primo post che troverai in bacheca "Pari mia nonna\\',
    'Apri Instagram e commenta sotto il primo post che troverai in bacheca "Oggi credo mangerò una scatoletta di tonno\\',
    'Partendo da te in senso orario dovrete dire un sinonimo della parola "combattere\\',
    'Per i prossimi 3 minuti parlerai come un ventriloquo. Quindi indossa un calzino nella tua mano e parla muovendo la "marionetta\\',
    'Chi sta leggendo ad alta voce per tutti è un grande ogni tanto dovrete chiamarlo "Prof.\\',
    'Partendo da te in senso orario dovrete dire un sinonimo della parola "sfida\\',
    'Hai 30 secondi per scrivere "barbari" tramite messaggio su WhatsApp ad un altro dei giocatore usando solo il naso, se non ce la fai bevi x1',
    'Hai 30 secondi per scrivere "Estonia" tramite messaggio su WhatsApp ad un altro dei giocatore usando solo il naso, se non ce la fai bevi x1',
    'Hai 30 secondi per scrivere "0123456789" tramite messaggio su WhatsApp ad un altro dei giocatore usando solo il naso, se non ce la fai bevi x1',
    'Partendo da te in senso orario dovrete dire un sinonimo di "voler bene"',
    'Partendo da te in senso orario dovrete dire un sinonimo della parola "odiare"',
    'Partendo da te in senso orario dovrete dire un sinonimo della parola "prostituta"',
    'Partendo da te in senso orario dovrete dire un sinonimo di "fare sesso"',
    'Partendo da te in senso orario dovrete dire un sinonimo della parola "bagno"',
    'Giocate tutti, si parte da te e si prosegue in ordine cronologico rispetto a come siete disposti. Scegli una lettera dell\'alfabeto italiano (esempio "f") il giocatore successivo aggiunge un’altra lettera alla lettera precedente (esempio "fi"), quello successivo un’altra e così via. Chi termina la parola (ad esempio "fiacco") e non sa come continuarla per formare un\'altra parola (esempio "fiaccolata"), ha perso e beve x1. Attenzione: è possibile chiedere la parola al giocatore precedente se si pensa che non esista la sequenza di lettere composta e se effettivamente il giocatore non lo sa o la parola non esiste nel dizionario italiano beve lui x1.',
    'Scegli un oggetto! Gli altri giocatori hanno 20 domande in totale a cui dovrai rispondere "sì" o "no" per poter capire di cosa si tratta e provare a indovinare',
    'Scegli un oggetto che si potrebbe trovare facilmente in uno stadio! Gli altri giocatori hanno 20 domande in totale a cui dovrai rispondere "sì" o "no" per poter capire di cosa si tratta e provare a indovinare, se sbagliano a indovinare passate le 20 domande bevono x1!',
    'Scegli un oggetto che si potrebbe trovare sicuramente in un minimarket! Gli altri giocatori hanno 20 domande in totale a cui dovrai rispondere "sì" o "no" per poter capire di cosa si tratta e provare a indovinare, se sbagliano a indovinare passate le 20 domande bevono x1!',
    'Scegli un oggetto che si potrebbe trovare facilmente in una camera di un bebè! Gli altri giocatori hanno 20 domande in totale a cui dovrai rispondere "sì" o "no" per poter capire di cosa si tratta e provare a indovinare, se sbagliano a indovinare passate le 20 domande bevono x1!',
    'Scegli un oggetto che si potrebbe trovare facilmente in una cucina! Gli altri giocatori hanno 20 domande in totale a cui dovrai rispondere "sì" o "no" per poter capire di cosa si tratta e provare a indovinare, se sbagliano a indovinare passate le 20 domande bevono x1!',
    'Scegli un oggetto che si potrebbe trovare facilmente in una chiesa cattolica! Gli altri giocatori hanno 20 domande in totale a cui dovrai rispondere "sì" o "no" per poter capire di cosa si tratta e provare a indovinare, se sbagliano a indovinare passate le 20 domande bevono x1!',
    'Il prossimo giocatore che dice "cioè" dovrà bere x1!',
    'Il prossimo giocatore che dice "purtroppo" dovrà bere x1!',
    'Il prossimo giocatore che dirà "così" dovrà bere x1!',
    'Il prossimo giocatore che dirà "sempre" dovrà bere x1!',
    'Il prossimo giocatore che dirà "quando" dovrà bere x1!',
    'Il prossimo giocatore che dirà "caldo" o "freddo" dovrà bere x1!',
  ],
  femmina: [
    'Scegli un ragazzo che avrà la possibilità di farti una nuova acconciatura di capelli',
    'Vota il giocatore uomo che secondo te ha più muscoli',
    'Verità! Questa è la vendetta degli ex! Bevi x1/2 per tutte le volte che hai lasciato!',
    'Premio per chi si distingue dalla massa; se hai i capelli corti bevi x1/2! Come dici? Non è un premio? Ah scusa... va beh bevilo lo stesso.',
    'Scegli se un ragazzo ti dovrà mettere del fard in faccia o bevi x1. Se non avete del fard a disposizione bevi x1/2.',
    'Fatti truccare da un giocatore maschio a tua scelta oppure bevi x1',
    "Comunque io sta cosa che le ragazze sono generalmente più basse dei ragazzi non l'ho mica capita... Stai in piedi sulla sedia per i prossimi 5 minuti",
    'Mettiti dei tacchi se ce li hai a disposizione',
    'Balla la danza del ventre con musica a tema in sottofondo per 1 minuto (se non sai come fare guarda un tutorial)',
    'Lo so... sei una bella ragazza e starai pensando quanto sono brutti i partecipanti maschi al gioco. Non ti preoccupare, abbiamo una soluzione per te: ',
    'In questa sfida scegli te come suddividerti le bevute in rapporto alla difficoltà dell\'esercizio fisico "Jamping Jacks"',
    'finché un giocatore non ripeterà un sinonimo già detto o non avrà più idee e dovrà bere x1/2!',
    'Scegli un giocatore che ti tenga le gambe ferme mentre effettui 10 ripetizio',
    'se non hai coraggio bevi x1!',
    'se non hai coraggio bevi x1!',
    'finché un giocatore non ripeterà un sinonimo già detto o non avrà più idee e dov',
    'finché un giocatore non ripeterà un sinonimo già detto o non avrà più idee e dovrà bere x1/2!',
    'finché un giocatore non ripeterà un sinonimo già detto o non avrà più idee e dovrà bere x1/2!',
    'finché un giocatore non ripeterà un sinonimo già detto o non avrà più idee e dovrà bere x1/2!',
    'finché un giocatore non ripeterà un sinonimo già detto o non avrà più idee e dovrà bere x1/2!',
    'finché un giocatore non ripeterà un sinonimo già detto o',
    'avrà più idee e dovrà bere x1/2!',
  ],
}
