export default {
  maschio: [
    'Toccati il pacco per 5 secondi',
    'Da adesso finché non dovrai bere ogni inizio turno dovrai toccarti il pacco per 5 secondi',
    'Per i prossimi 5 turni ogni volta che parlerai dovrai farlo toccandoti il pacco',
    'Verità! Baceresti mai un uomo per soldi? Se sì quanti?',
    'Verità! Se ti sei mai masturbato in un luogo pubblico bevi x1!',
    'Prendi in braccio la persona meno pensante tra tutti i giocatori presenti e fai 3 mezzi squat con essa in braccio. Lo so, può essere molto difficile... infatti se non ce la fai bevi x1/2! Scarso!',
    'Cerca su una piattaforma video "Balli ragazzi tiktok" e imita alla perfezione i primi 5 tiktok che compaiono senza poterli scegliere te. Imitarli alla perfezione significa che una volta finito un tiktok gli altri giocatori dovranno dire se sono soddisfatti della tua prestazione oppure no e in caso contrario dovrai rifarlo!',
    'Scegli una giocatore di sesso femminile in modo randomico alla quale devi fare un baciamano partendo dalla mano e arrivando fino alla spalla molto lentamente',
    'Se siete in un periodo compreso tra ottobre e aprile, la prossima volta che una ragazza esce sul balcone dovrai abbracciarla per tutto il tempo che starà fuori ',
    'Mostra il tuo muscolo più possente,Dai un bacio sul collo ad un giocatore di sesso opposto al tuo',
    "Se indossi dei pantaloncini o un costume fatti un risvoltino, ma non dalla parte delle gambe ma dalla parte del busto.. così farai vedere un po' di stacco-coscia in più caro",
    'Effettua la posizione yoga "VIRABHADRASANA I" e rimani in posizione per 30 secondi.',
    'Effettua la posizione yoga "Triangolo Esteso" e rimani in posizione per 30 secondi',
    'Effettua la posizione yoga "Locusta" e rimani in posizione per 30 secondi',
    'A meno che già non lo indossi, indossa per questo turno un pantalone che si chiuda con il laccio e facci un fiocco ben saldo. Tutte i gocatori donna dovranno cercare di slacciare il laccio con il solo uso della bocca in meno di 20 secondi, chi non ci riesce beve x1!',
    'Fai un massaggio professionale di 10 minuti ad un giocatore scelto randomicamente, scegli tu quando farglielo',
    'Verità! Ti ricordi il primo porno con cui sei venuto? Raccontacelo! Puoi non rispondere bevendo x1/2!',
    'Finché non dovrai bere rimani con le gambe incrociate, lo so è fastidioso ma secondo te perché te lo faccio fare?',
    "Spero che tu sia un ragazzotto muscoloso, perché dovrai faticare bello! Scegli a sorte un giocatore tra quelli meno pesanti di te, il quale dovrà stare in piedi con le gambe rigide quindi senza possibilità di muovere o piegare le gambe. Il tuo compito è quello di sollevarlo da terra per fargli toccare il soffitto con tutto il palmo della mano, se non ce la fate tu bevi x1 l'altro giocatore x1/2",
    "Spero che tu sia un ragazzotto muscoloso, perché dovrai faticare bello! Scegli a sorte un giocatore tra quelli meno pesanti di te, il quale dovrà stare in piedi con le gambe rigide quindi senza possibilità di piegare le gambe. Il tuo compito è quello di sollevarlo da terra per fargli toccare il soffitto con il gomito, se non ce la fate tu bevi x1 l'altro giocatore x1/2",
    'Spero che tu sia un ragazzotto muscoloso, perché dovrai faticare bello! Scegli a sorte un giocatore tra quelli meno pesanti di te, il quale dovrà stare in piedi con le gambe rigide quindi senza possibilità di muovere o piegare le gambe. Il tuo compito è quello di sollevarlo da terra per fargli toccare il soffitto con tutto il palmo della mano per 10 secondi di fila, se non ce la fate entrambi bevete x1/2!',
    "Se ce l'hai a disposizione bevi un bicchiere intero di succo d'ananas! Lo sanno tutti che migliora il sapore del tuo sp... Emh, dai insomma, ci siamo capiti. ",
    'Verità! Che tipo di mutanda stai indossando, slip o boxer? Di che colore? E di che marca?',
    'Verità! Raro ma... Qualche ragazza ci ha mai provato con te senza conoscerti?',
  ],
  unisex: [
    "Verità! Qual'è la tua prima posizione fatta? Puoi non rispondere bevendo x1/2!",
    "Scegli un giocatore del sesso opposto al tuo con cui fare questa sfida. L'uomo si sdraia a terra con la pancia in sù e la donna sopra di lui con la pancia in giù. State così per 3 minuti.",
    "Scegli un giocatore del sesso opposto al tuo con cui fare questa sfida. L'uomo si sdraia a terra con la pancia in sù e la donna sopra di lui con la pancia in sù. State così per 3 minuti.",
    "Se indossi una maglietta un prescelto dovrà riempire un bicchiere d'acqua e bagnartela... Puoi fermare tutto questo bevendo x1!",
    "Qual'è il giusto numero per te di rapporti alla settimana?",
    "È giunta l'ora dell'agonia per te! Stai in piedi con le gambe leggermente divaricate. Ogni giocatore prenderà un cubetto di ghiaccio e lo farà scorrere lungo il tuo corpo finché non si scioglieranno.",
    'Verità! Quali devono essere i punti di forza di una persona per attrarti fisicamente? Fammi una classifica dei primi 5',
    "Verità! Ha in in programma di far l'amore nelle prossime 24h?",
    'Verità! Mai fatto il bagno al mare completamente nudo/a?',
    'Verità! Se dovessi scegliere andresti a letto con una persona che ha 6 anni in più o in meno di te?',
    'Verità! Andresti mai in una spiaggia nudista?',
    'Verità! Quale secondo te è il tuo punto forte per riuscire a rimorchiare?',
    "Verità! Preferisci che l'organo riproduttivo del tuo partner ideale sia rasato/a o peloso/a? Quanto è importante da 1 a 10?",
    'Verità! Facci una tua personale top 3 delle migliori posizioni sessuali',
    'Verità! Hai mai avuto un rapporto sessuale con una persona che non conoscevi?',
    'Verità! Staresti nuovamente insieme a un ex che hai avuto? Se sì perché?',
    'Verità! Faresti mai una cosa a tre?',
    'Sbottonati tutti i bottoni, slaccia tutti i lacci e apri tutte le cerniere che hai su qualsiasi vestito',
    'Scegli un partener del sesso opposto al tuo in modo randomico e fate la posizione yoga di coppia "Front Bird" rimanendo in posizione per almeno 5 secondi. Obbligatorio provarci ma se non ce la fate bevete x1/2 a testa.',
    'Scegli un partener del sesso opposto al tuo in modo randomico e fate la posizione yoga di coppia "Il pesce sollevato" rimanendo in posizione per almeno 5 secondi. Obbligatorio provarci ma se non ce la fate bevete x1/2 a testa.',
    'Prova a far venire i brividi ad una persona del sesso opposto al tuo in qualsiasi modo possibile in 45 secondi, se non ci riesci bevi x1/2!',
    'Chiedi a un assistente vocale di scegliere un numero compreso tra 0 e 25, il numero che uscirà saranno le ripetizioni dell\'esercizio "camminata sulle mani" che dovrai fare come penitenza! Pensala posi',
    "Fai scorrere il tuo labbro inferiore sul collo di un giocatore opposto al tuo sesso, partendo dalla clavicola per finire dietro l'orecchio, puoi rifiutarti bevendo x1!",
    'Effettua la posizione yoga "VIRABHADRASANA III" e rimani in posizione per 30 secondi',
    'Effettua la posizione yoga "mezza luna" e rimani in posizione per 30 secondi',
    'Bacia il collo per 40 secondi di una persona del sesso opposto al tuo scelta in modo randomico,Sei capace a',
    "Scegli in modo randomico un giocatore a cui dovrai fare un massaggio al collo per 5 minuti, se una sfida ostruisce l'esecuzione di questa mettetela in pausa e riprendetela appena potete",
    "Scegli in modo randomico un giocatore a cui dovrai fare un massaggio ad una parte del corpo scelta dal fortunato massaggiato per 5 minuti, se una sfida ostruisce l'esecuzione di questa mettetela in pausa e riprendetela appena potete.",
    "Scegli in modo randomico un giocatore che dovrà farti un massaggio ad una parte del corpo scelta da te per 5 minuti, se una sfida ostruisce l'esecuzione di questa mettetela in pausa e riprendetela appena potete.",
    "Scegli in modo randomico un giocatore che dovrà farti un massaggio alla schiena per 5 minuti, se una sfida ostruisce l'esecuzione di questa mettetela in pausa e riprendetela appena potete.",
    'Sii più provocante possibile nel sussurarre il tipo di bianacheria che indossi al giocatore del sesso opposto al tuo più vicino a te per almeno 20 secondi! Sbizzarrisciti con la fantasia!',
    'Solletico no stop da parte di tutti i giocatori per 20 secondi te non potrai rispondere!',
    'Verità! Hai mai fatto un rapporto anale? Se no, avresti la curiosità di provare?',
    'Verità! Hai mai avuto una fantasia sessuale su un/una professore/essa? Se sì, su chi?',
    'Tra questi rapporti cosa non hai mai provato? Auto-masturbazione, masturbazione del partner, sesso standard, sesso con oggetti, sesso anale, sesso orale (ricevente), sesso orale (praticante) e spagnola.',
    "Te e un giocatore scelto randomicamente state chiusi nel posto più piccolo che c'è in casa (es. sgabuzzino, doccia, spazio stretto tra due mobili) per almeno 5 minuti e se una sfida è chiaramente impossibile da eseguire, continuate questa e la farete più tardi.",
  ],
  femmina: [
    'Strizzati le tette per 5 volte',
    'Da adesso finché non dovrai bere ogni inizio turno dovrai strizzarti tette per 5 volte',
    'Per i prossimi 5 turni ogni volta che parlerai dovrai farlo strizzandoti le tette',
    'Verità! Baceresti mai una donna per soldi? Se sì quanti?',
    "Verità! Quand'è l'ultima volta che ti sei masturbata? Se rispondi che non ti sei mai masturbata bevi x1 perché è una cazzata.",
    'Siediti sulle gambe di un giocatore maschio scelto da te per i prossimi 15 minuti (le future sfide hanno la precedenza su questa, quindi se dovessero',
    'Cerca su una piattaforma video "Balli ragazze tiktok" e imita alla perfezione i primi 5 tiktok che compaiono senza poterli scegliere te. Imitarli alla perfezione significa che una volta finito un tiktok gli altri giocatori dovranno dire se sono soddisfatti della tua prestazione oppure no e in cas',
    'Siediti a cavalcioni sulle gambe di un giocatore maschio scelto da te per 15 minuti (le future sfide hanno la precedenza su questa, quindi se dove',
    'Siediti sulle gambe di un giocatore maschio scelto da te dandogli le spalle per 15 minuti (le future sfide hanno la precedenza su questa, quindi s',
    'Vai su internet o su una piattaforma video e cerca "esercizi stretching" dovresti trovare vari video tutorial di svariati minuti, scegline uno in ',
    'Mettiamo alla prova i maschietti, quegli incapaci! Se indossi il reggiseno Scegli un maschio che entro 15 secondi dovrà cercare di slacciarti il r',
    "Indovina l'oggetto challenge? Bendati e siediti, ogni giocatore sceglierà 2 oggetti commestibili (es frutta o verdura) oppure una sua parte del corpo e lo avvicinerà alla tua bocca, il tuo obbiettivo è quello di indovinare di cosa si tratta con il solo utilizzo della bocca e della lingua (vietato",
    'Secondo una ricerca neozelandese la posizione più di comfort e rilassante per una donna è quella dove la donna è sdraiata a pancia in giù con una serie di cuscini sotto il ventre in modo da alzare il bacino il più possibile rispetto al resto del corpo ch invece rimane sdraiato a terra. L\'altezza a cui deve arrivare il bacino è all\'incirca a 40cm dalla superficie dove poggia il resto del corpo. Quindi se da ora in poi ci sarà una sfida dove dovrai ricevere un "massaggio rilassante" dovrai rimanere obbligatoriamente bendata e dovrai provare a emulare questo metodo. A fine massaggio facci sapere ',
    'Mettiti piegata in modo da mantenere fermo un bicchiere di plastica posto sulla tua schiena, ora prova a fargli fare mezzo giro senza farlo cadere,',
    "Più c'è pene meglio è! Calcola il numero di tette femminili presenti nella stanza e dividili per il numero di peni presenti nella stanza. Ecco ques",
    "Sapevi che il kiwi è un frutto che migliora la sensazioni sessuali in una donna? Tutto ciò è possibile dagli acidi grassi polinsaturi omega3... beh sì, il pesce ne ha molti di più ma poi ti puzzerebbe l'alito e noi non vogliamo fare brutte figure giusto? Ottimo, quindi se hai un kiwi a disposizione mangialo! Oppure se proprio vuoi fare la figura della scaricatrice di porto mangiarti una puzzosissima scatoletta di tonno, poi non ti lamentare se ",
    'Verità! Hai mai utilizzato a tuo vantaggio il fatto che una persona era invaghita di te? Se sì, racconta quando è successo',
  ],
}
